from django.contrib.auth import get_user_model #Helps getting currently logged in users informations
from django.contrib.auth.forms import UserCreationForm #Helps creating a User table

class UserCreateForm(UserCreationForm):
    #UserCreationForm class creates a User table with the current users username, email, password and verified password

    class Meta:
        fields = ('username','email','password1','password2') #These will be the newly created User tables fields
        model = get_user_model()    #get_user_model() generates currently logged in user's all records from database in a object

    def __init__(self,*args,**kwargs): #*args takes a list and *kwargs (key word arguments) takes a dictionary as input
        super().__init__(*args,**kwargs)
        self.fields['username'].label = 'Display Name'
        self.fields['email'].label = 'Email Address'

        """
        This block of code is just defining that the username and email box in the form for sign-up page
        generated by UserCreationForm class should have 'Display Name' and 'Email Address' as labels respectively.
        So, we are overriding the __init__() method of UserCreationForm class.
        """
